# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gabi Huiber
tagline:             'noodling in the data stream'
description:         'My notes on things I tinker with, or do for a living; the two overlap in places.'
themecredit:         'Built on <a href="http://lanyon.getpoole.com" target="_blank">Lanyon</a>, a reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://ghuiber.github.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Gabi Huiber
  url:               https://twitter.com/ghuiber
  email:             ghuiber@gmail.com

# Custom vars
version:             1.0.0

# Tracking
google_analytics: UA-2487306-2

# Comments
disqus: ghuibergithubio

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
   - jekyll-redirect-from
