# Site settings
title: Noodling in the data stream
email: ghuiber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My notes on things I tinker with, or do for a living.

url:     http://www.enoriver.net # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

so_username: Gabi
github_username:  ghuiber

# Build settings
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:           pretty

# Tracking
google_analytics: UA-2487306-2

# Comments
disqus: enorivernet
